repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
          - id: trailing-whitespace
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.39.0
      hooks:
          - id: markdownlint
   - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.6
      hooks:
          - id: shellcheck