# Lint the script with shellcheck

name: Shellcheck on vuln2pve
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: shellcheck vuln2pve
